stages:
  - release

package_release:
  image: hacksawgaming/hacksaw-build:4.0.0-rc.1-4
  stage: release
  before_script:
    - apk add --update zip
    - npm i
  script:
    - $(npm bin)/gitlab-ci-releaser --npm
  only:
    refs:
      - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^\d+\.\d+\.\d+/ 

package_rc:
  image: hacksawgaming/hacksaw-build:4.0.0-rc.1-4
  stage: release
  before_script:
    - apk add --update zip
    - pnpm i
  script:
    - npx gitlab-ci-releaser --npm --preid rc
  only:
    - develop
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^\d+\.\d+\.\d+(?:-rc\.[0-9]+)?/
