stages:
  - release

package_release:
  image: hacksawgaming/hacksaw-build
  stage: release
  before_script:
    - apk add --update zip
    - npm i
  script:
    - $(npm bin)/gitlab-ci-releaser --npm
  only:
    - master

package_rc:
  image: hacksawgaming/hacksaw-build
  stage: release
  before_script:
    - apk add --update zip
    - npm i
  script:
    - $(npm bin)/gitlab-ci-releaser --npm --preid rc
  only:
    - develop
